import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TheHeader from "@/components/TheHeader";
import TheFooter from "@/components/footer/TheFooter";
import TheAside from "@/components/TheAside";
import { Providers } from "./store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <Providers>
         <TheHeader  />
         {/* <TheAside /> */}
         <main className="main">
         {children}

         </main>
         <TheFooter/>
         </Providers>
         </body>
    </html>
  );
}
